[package]
name = "frame_comp"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkanalia = { version = "0.31.0", features = ["libloading", "provisional", "window"]}
cgmath = "0.18.0"
anyhow = "1.0.100"
bytemuck = { version = "1.24.0", features = ["derive"] }
derive_builder = "0.20.2"